### ISSUE TITLE
Error running JBuilder 6 (which requires Java 1.5)

### ISSUE THREAD

**Issue by sonicspider** [bric3/osx-jdk5-installer#3]
Getting a strange error from the JBuilder startup after installing 1.5, and was wondering if anyone had some thoughts on it.. (BTW... tried to run JavaPreferences.app and got the exact same error..)

Caused by: java.lang.UnsatisfiedLinkError: /System/Library/Frameworks/JavaVM.framework/Versions/1.5.0_30/Libraries/liblaf.jnilib:  
Symbol not found: _kCUIWidgetTickMarks  
Referenced from: /System/Library/Frameworks/JavaVM.framework/Versions/1.5.0_30/Libraries/liblaf.jnilib  
CFExpected in: /System/Library/PrivateFrameworks/CoreUI.framework/Versions/A/CoreUI 

I've been google this and so far, no joy..

**Comment by bric3** [comment]
Hi,

I'm not using JDK5 code and applications anymore. But I _believe_ / _fear_ that Apple did significant changes in the OS so that the binary compatibility is broken in Yosemite / El Capitan (at least for graphical applications). Note I never ran graphical applications before. I'm not sure they were working correctly before

What is your OS by the way ?

**Comment by sonicspider** [comment]
Just upgraded to Yosemite...  I have been avoiding upgrades since Mavericks because of this very issue. It is a major client's  web application (and they spend a lot of money...)  I use JBuilder 6 because it is the last JBuilder that used the Primetime framework (which I really like and is WAY better than Eclipse framework)  It is the JBuilder IDE that is farkling..   I'm testing JBuilder 8 (uses Eclipse framework) now, I guess I need to bite the bullet.. Hey, I dodged that bullet for 10 years.. I guess I'm lucking I lasted that long, in a weird sort of way..

Thanks a lot for your work on the script, it has been a life saver in the past, every time Apple wants to update Java or do a patch... (and proceed to nuke Java settings)

**Comment by bric3** [comment]
Maybe there's a solution, but that would require much more investigation/knowledge maybe even disassembling. I'm not ready to spend yet or at all that much time anymore ;)

On another note you definitely want to try IntelliJ IDEA, they have implemented a nice IDE that is feature rich. However I don't know about Primetime or other framework of this kind as I'm more of a server backend developer.

**Comment by sonicspider** [comment]
Primetime was an IDE framework much like Eclipse built by Borland in the 90s.  I was a member of Borland's TeamB for JBuilder at the time.  Borland did not understand the importance of open sourcing and therefore allowed Eclipse to dominate, eventually making their efforts with JBuilder become unsustainable as a profit center. (People wouldn't even try JBuilder because it was so dam expensive, didn't matter that it was far superior.)  In 2007 they finally moved JBuilder over to Eclipse and in doing so totally trashed JBuilder IMO..  It was the best, still is..  I only did back end work in Java as well..  Thanks for your feedback..
